### ISSUE TITLE
Link in readme

### ISSUE THREAD

**Issue by frimdo** [cpuguy83/docker-nfs-server#15]
In redme there is a link `http://www.tech-d.net/2014/03/29/docker-quicktip-4-remote-volumes/`, which leads to non related webpage.

**Comment by cpuguy83** [comment]
Wow, that's like the best webpage ever.

The domain unfortunately lapsed awhile back and I hadn't realized.
But in any case I have a different domain that's good. Updated the link.

Thanks!
