### ISSUE TITLE
Run on Rancher, fails with cannot create directory '/etc/services': File exists

### ISSUE THREAD

**Issue by Richard87** [cpuguy83/docker-nfs-server#16]
Hi, I'm trying to run this on Rancher with this `docker-compose.yml`-file:

    version: '2'
    services:
      docker-nfs:
        privileged: true
        image: cpuguy83/nfs-server
        volumes:
        - /mnt/volume-fra1-01:/exports
        pid: host
        ports:
        - 2049:2049/tcp
        - 111:111/udp
        command:
        - /exports
        - /etc/services:/etc/services:ro

But it fails with this error:

    7/14/2017 11:50:18 PMmkdir: cannot create directory '/etc/services': File exists

Hope it's okay that I open an issue here, I don't know how to fix this!

**Comment by cpuguy83** [comment]
That's because `/etc/services` in the container is a file, and `/etc/services` on your host is a dir, and you can't bindmount a dir onto a file.

Closing since it's not an issue.

**Comment by Richard87** [comment]
Thanks for the quick answer, any tips on how to fix it? If I remove /etc/services from the command, it still stops on the same error :/

**Comment by cpuguy83** [comment]
What do you mean if you remove it?

**Comment by Richard87** [comment]
Like this:

    version: '2'
    services:
      docker-nfs:
        privileged: true
        image: cpuguy83/nfs-server
        volumes:
        - /mnt/volume-fra1-01:/exports
        pid: host
        ports:
        - 2049:2049/tcp
        - 111:111/udp
        command:
        - /exports
      #- /etc/services:/etc/services:ro

**Comment by cpuguy83** [comment]
Are you sure this is updating? If there's nothing doing a mount over `/etc/services` you shouldn't be getting an error about it.

**Comment by Richard87** [comment]
Hi, no, I'm not sure... Also I got another NFS solution working, so I'll close this issue :)
