### ISSUE TITLE
NFS Swarm Service?

### ISSUE THREAD

**Issue by ns-cweber** [cpuguy83/docker-nfs-server#18]
I'm at a loss for how to run this as a Swarm service, since there is no service equivalent for `--privileged` as far as I can tell. Is this possible?

**Comment by alexz-kh** [comment]
You should ask those guys 
https://github.com/moby/moby/issues/24862
in general, nfs require access to kernel, so no un-privileged container in nearest time will be...

**Comment by cpuguy83** [comment]
That's correct, it's not possible to run this on swarm.
