### ISSUE TITLE
Not starting NFS kernel

### ISSUE THREAD

**Issue by mjo09a** [cpuguy83/docker-nfs-server#3]
When I run the docker I keep getting  \* Not starting NFS kernel daemon: no support in current kernel.
Setting up watches.
Watches established. in the log file.

**Comment by kiwenlau** [comment]
@vladimirshestak 

I have the same issue when run **cpuguy83/nfs-serve** on **ubuntu 14.04** host.

And just load nfs kernel modules solves my problem! Thank you!

```
modprobe nfs
modprobe nfsd
```

**Comment by wzymaster** [comment]
I experienced the same issue on redhat 7.2, any solution so far ?
