### ISSUE TITLE
NFS Client only works on same host as NFS server

### ISSUE THREAD

**Issue by sylus** [cpuguy83/docker-nfs-server#6]
I have been playing around with your awesome work on NFS for docker but am currently having a problem was hoping you could help me with:

First I made sure the kernel had the appropriate mods:

sudo modprobe nfs
sudo modprobe nfsd

Scenario 1 (Client on same VM)

docker run -d -p 2049:2049 --name nfs-server --privileged cpuguy83/docker-nfs-server /home
docker run -d --name nfs-client --link nfs-server:nfs --privileged -v /mnt cpuguy83/docker-nfs-client /home:/mnt

Since the nfs-client is on the same server I can use --link and everything works great without issue

Scenario 2 (Client on different VM)

docker run -d -p 2049:2049 --name nfs-server --privileged cpuguy83/docker-nfs-server /home
docker run -d --name nfs-client -e NFS_PORT_2049_TCP_ADDR=ip_address --privileged -v /mnt cpuguy83/docker-nfs-client /home:/mnt

This scenario fails for me no matter what IP address I try. I have tried both COREOS_PUBLIC_IP and COREOS_PRIVATE_IP and they don't work. Is there anything special I need to do as can no longer use internal ip's from docker since the client is on a separate host and an IP of 10.0.0.1 won't be anything in this context.

Appreciate any guidance!

**Comment by sylus** [comment]
Thought I would add a working scenario across different VMs

Scenario 3 (Client on different VM)

docker run --net host -d --name nfs-server --privileged dockdrop/docker-nfs-server /home
docker run -d --name nfs-client -e NFS_PORT_2049_TCP_ADDR=172.17.8.101 --privileged -v /mnt dockdrop/docker-nfs-client /home:/mnt

This scenario works but most certaintly not the recommended way with the use of --net host. However it does work. Ideally it would be great to figure out why Scenario 2 is not working.

**Comment by cpuguy83** [comment]
I don't think the nfs traffic likes to be nat'd, whcih is what happens when you do "-p <port>:<port>" and then connect to the host.

So you'll need to setup your container networks such that containers on different hosts can communicate, or use --net=host has you did above.
