### ISSUE TITLE
how do i mount the volume from a remote client?

### ISSUE THREAD

**Issue by hwongcom** [cpuguy83/docker-nfs-server#7]
I would like to mount the volume from a remote client. how can i do that?

e.g. i've already set up the nfs server docker container but i'm not sure how this container's nfs directory can be accessed from the remote client.

i've went inside the nfs server container but i cant seem to do "service nfs start". is this normal?

**Comment by hwongcom** [comment]
i would like to use the docker nfs container as a pxe boot server for my pxe boot clients. do u have any guides on how to get this done?

**Comment by cpuguy83** [comment]
https://github.com/cpuguy83/docker-nfs-client
